---
- name: Install python3 and required system packages
  hosts: k8s
  gather_facts: no
  become: yes
  tasks:
   - name: Install python3
     apt: update_cache=yes name=python3 state=present 
   - name: Install required system packages
     apt:
       name: python3-pip
       state: present       
   - name: Install requirements python module
     pip:
       name:
        - openshift
        - pyyaml
        - kubernetes

- name: Deploy app in new namespace 
  hosts: k8s
  gather_facts: no
  tasks:
   - name: Create a new k8s namespace
     k8s:
       name: my-app
       api_version: v1
       kind: Namespace
       state: present
       kubeconfig: ~/.kube/config
   - name: Create directory for app deployment
     file:
       state: directory
       path: ~/k8s
       mode: 755
   - name: Copy app file in directory
     copy: 
       src: ./apps/nginx-config.yaml
       dest: ~/k8s/nginx-config.yaml
   - name: Deploy nginx app in kubernetes
     k8s:
       src: ~/k8s/nginx-config.yaml
       state: present
       namespace: my-app
       kubeconfig: ~/.kube/config    
